apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: app
data:
  KAFKA_BOOTSTRAP: "kafka.platform.svc.cluster.local:9092"
  MONGO_URL: "mongodb://mongo.platform.svc.cluster.local:27017/ca3"
---
apiVersion: v1
kind: Secret
metadata:
  name: processor-secrets
  namespace: app
type: Opaque
stringData:
  # add secrets here if you have any (passwords, tokens)
  DUMMY: "x"
