apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: platform
spec:
  serviceName: mongo
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongod
          image: mongo:6
          args: ["--bind_ip_all"]
          ports: [{containerPort: 27017, name: mongo}]
          readinessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - { name: data, mountPath: /data/db }
      volumes:
        - name: data
          emptyDir: {}   # MVP: no PV
